/* AUTO-GENERATED by 实验/gen_tokenizer_tables.py — 勿手改 */
#ifndef MT_TOK_TABLES_H
#define MT_TOK_TABLES_H
#include <stdint.h>

#define TOK_VOCAB_SIZE 30008
#define TOK_N_SYM      29991
#define TOK_N_MERGES   51203
#define TOK_SPECIAL_MAX_ID 7

extern const uint32_t TOK_OFF[];
extern const uint8_t  TOK_BLOB[];
extern const uint8_t  TOK_IS_SPECIAL[];
extern const int32_t  TOK_SYM2VOCAB[];
extern const uint32_t TOK_MERGE_LEFT[];
extern const uint32_t TOK_MERGE_RIGHT[];
extern const uint32_t TOK_MERGE_RESULT[];

typedef struct { uint32_t lo, hi; } tok_range_t;
extern const tok_range_t TOK_LETTER[]; extern const int TOK_N_LETTER;
extern const tok_range_t TOK_NUMBER[]; extern const int TOK_N_NUMBER;
extern const tok_range_t TOK_SPACE[];  extern const int TOK_N_SPACE;

#endif
